# to make the hook (listener) to the pipe line

name: "CI/CD pipeline for lms frontend"
on: # adding a listener to listen to the push events that do to the main branche
  push:
    branches:
      - main

# giving the jobs and steps
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checking out the repo
        uses: actions/checkout@v3

      - name: Installing Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18 # we use this 18 node version in our app

      - name: Installing SASS # download sass
        run: npm i -g sass

      - name: Compiling scss files to css 
        run: sass scss:css
      
      - name: Zipping to deploy 
        run: zip -r dist.zip css pages js index.html
      
      - name: Authentication to Google cloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ SERVICE_ACCOUNT_PRIVATE_KEY }}'

      - name: Set up Cloud 
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Deploying the zip'
        run: gcloud compute scp --zone="asia-south1-a" dist.zip root@dep-9-vm:/opt/apache/apache-tomcat-10.1.1/webapps/lms-backend

      - name: Cleanup old stuff
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo rm -rf /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/css 
          /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/pages 
          /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/js 
          /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/index.html
          "
      - name: Extracting the zip 
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo unzip /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/dist.zip -d /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend"

      - name: Cleaning leftovers
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo rm /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/dist.zip"



      




